export { GitService, type IGitService, type IGitDiffResult, type IGitDiffError, type GitDiffOutcome, type IGitBranchInfo } from "./git/GitService"
export { GitRunner, GitUnavailableError, makeNonInteractiveEnv, GIT_MAX_BUFFER, type IGitRunner, type IGitRunOptions, type IGitRunResult } from "./git/GitRunner"
export { SnapshotService, SnapshotStore, SnapshotError, type ISnapshotService, type ISnapshotStore, type ISnapshotPatch, type ISnapshotRecord, type IRevertResult } from "./snapshot"
export { PermissionManager, type IPermissionManager } from "./permission/PermissionManager"
export { NotificationService } from "./notification/NotificationService"
export type { INotificationService, NotificationType, INotificationServiceOptions } from "./notification/NotificationService"
export { BackendHealthMonitor } from "./health/BackendHealthMonitor"
export { CommitMessageService, type ICommitMessageService } from "./commit-message/CommitMessageService"
export { AutocompleteService, LANGUAGE_COMPLETIONS } from "./autocomplete/AutocompleteService"
export type { ILanguageCompletionConfig } from "./autocomplete/AutocompleteService"
export { TelemetryService } from "./telemetry/TelemetryService"
export type { TelemetryEventName, ITelemetryProps, ITelemetryService } from "./telemetry/TelemetryService"
export { CodebaseIndexer } from "./indexing/CodebaseIndexer"
export type { ICodebaseIndexer, IndexingState } from "./indexing/CodebaseIndexer"
export { IndexingStatusBar } from "./indexing/IndexingStatusBar"
export { StatusBarIndicator } from "./StatusBarIndicator"
