export { GitService, type IGitService, type GitDiffResult, type GitDiffError, type GitDiffOutcome, type GitBranchInfo } from "./git/GitService"
export { PermissionManager, type IPermissionManager } from "./permission/PermissionManager"
export { NotificationService } from "./notification/NotificationService"
export type { INotificationService, NotificationType, NotificationServiceOptions } from "./notification/NotificationService"
export { BackendHealthMonitor } from "./health/BackendHealthMonitor"
export { CommitMessageService, type ICommitMessageService } from "./commit-message/CommitMessageService"
export { AutocompleteService, LANGUAGE_COMPLETIONS } from "./autocomplete/AutocompleteService"
export type { LanguageCompletionConfig } from "./autocomplete/AutocompleteService"
export { TelemetryService } from "./telemetry/TelemetryService"
export type { TelemetryEventName, TelemetryProps, ITelemetryService } from "./telemetry/TelemetryService"
export { CodebaseIndexer } from "./indexing/CodebaseIndexer"
export type { ICodebaseIndexer, IndexingState } from "./indexing/CodebaseIndexer"
export { IndexingStatusBar } from "./indexing/IndexingStatusBar"
export { StatusBarIndicator } from "./StatusBarIndicator"
